#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -d freestanding_headers ] || git clone https://github.com/mintsuki/freestanding_headers.git
[ -d limine-efi ] || git clone https://github.com/limine-bootloader/limine-efi.git

automake_libdir="$(automake --print-libdir)"

mkdir -p build-aux
cp "${automake_libdir}/install-sh" build-aux

autoconf
