#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

: "${AUTORECONF:=autoreconf}"
: "${AUTOMAKE:=automake}"

cd "$srcdir"

AUXFILES="config.guess config.sub install-sh"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            set +x
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

if ! test -f version; then
    clone_repo_commit \
        https://github.com/osdev0/freestanding-c-hdrs.git \
        freestanding-c-hdrs \
        38fed4e1e3365733ddbfa03b0a28936243ad31e9

    clone_repo_commit \
        https://github.com/osdev0/cc-runtime.git \
        cc-runtime \
        dae79833b57a01b9fd3e359ee31def69f5ae899b
    cp cc-runtime/src/cc-runtime.c common/cc-runtime.s2.c

    clone_repo_commit \
        https://github.com/iczelia/pdgzip.git \
        pdgzip \
        010197664688f071b923615ea235ecb24963b61a
    cp pdgzip/pdgzip.c common/compress/pdgzip.c
    cp pdgzip/pdgzip.h common/compress/pdgzip.h

    clone_repo_commit \
        https://github.com/Limine-Bootloader/limine-protocol.git \
        limine-protocol \
        da65184e91f80fcb397270121b1e2515a11e01ee

    clone_repo_commit \
        https://github.com/PicoEFI/PicoEFI.git \
        picoefi \
        ca03047ab1edf9772842d1d71950ec442f5b2309

    clone_repo_commit \
        https://github.com/Mintsuki/Flanterm.git \
        flanterm \
        3e311fe2ce4f663273c22d1a229745bc53afa930

    clone_repo_commit \
        https://github.com/Mintsuki/stbi-hardened.git \
        stbi-hardened \
        b85b7e87f6f87300f32f7de3d94e1ed083a71263
    cp stbi-hardened/include/stb_image.h common/lib/stb_image.h
    patch -p0 < common/stb_image.patch
    rm -f common/lib/stb_image.h.orig

    clone_repo_commit \
        https://github.com/osdev0/libfdt.git \
        libfdt \
        7bf94e6347129d17eca263112296ad170dec28a9
fi

# Create timestamps file
if test -d .git && git log -1 >/dev/null 2>&1; then
    cat >timestamps <<EOF
REGEN_DATE="$(LC_ALL=C git log -1 --pretty=%cd --date='format:%B %Y')"
SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct)"
SOURCE_DATE_EPOCH_TOUCH="$(TZ=UTC0 git log -1 --pretty=%cd --date='format-local:%Y%m%d%H%M')"
EOF
else
    if ! test -f timestamps; then
        cat >timestamps <<EOF
REGEN_DATE="UNVERSIONED"
SOURCE_DATE_EPOCH="1546300800"
SOURCE_DATE_EPOCH_TOUCH="201901010000"
EOF
    fi
fi

for auxfile in $AUXFILES; do
    rm -f build-aux/$auxfile
done

$AUTORECONF -fvi -Wall

# Older versions of autoreconf have a bug where they do not
# install auxiliary files, sometimes... Check if that is the
# case and work around...
for auxfile in $AUXFILES; do
    if ! test -f build-aux/$auxfile; then
        if ! $AUTOMAKE --print-libdir >/dev/null 2>&1; then
            set +x
            echo "error: Broken autoreconf detected, but missing or broken automake." 1>&2
            echo "       Please make sure automake is installed and working." 1>&2
            exit 1
        fi
        AUTOMAKE_LIBDIR="$($AUTOMAKE --print-libdir)"
        if test -z "$AUTOMAKE_LIBDIR"; then
            # Assume `true` was passed as $AUTOMAKE
            continue
        fi
        mkdir -p build-aux
        cp -v "$AUTOMAKE_LIBDIR/$auxfile" build-aux/
        chmod +x build-aux/$auxfile
    fi
done

set +x

printf "\nSource tree bootstrapped successfully!\n"
