#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -d common/term ] || git clone https://github.com/limine-bootloader/terminal.git common/term
[ -f common/stb/stb_image.h ] || ( curl -Lo common/stb/stb_image.h https://github.com/nothings/stb/raw/master/stb_image.h && patch -p0 < common/stb_image.patch )
[ -f freestanding-toolchain ] || ( curl -Lo freestanding-toolchain https://github.com/mintsuki/freestanding-toolchain/raw/trunk/freestanding-toolchain && chmod +x freestanding-toolchain )
[ -d freestanding-headers ] || git clone https://github.com/mintsuki/freestanding-headers.git
[ -d limine-efi ] || git clone https://github.com/limine-bootloader/limine-efi.git
[ -d libgcc-binaries ] || git clone https://github.com/mintsuki/libgcc-binaries.git

autoreconf -fvi -Wall
