name: QEMU end-to-end tests

on: [push, pull_request]

jobs:
  qemu_test:
    name: QEMU end-to-end (x86_64, BIOS) tests
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git autoconf automake nasm curl mtools gzip llvm clang lld qemu-system-x86

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Bootstrap and configure
        run: ./bootstrap && ./configure --enable-werror --enable-bios --enable-uefi-x86-64

      - name: Run gzip QEMU test
        run: bash contrib/test_gzip_qemu.sh
